# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
  cache-name: note


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.18.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install
      run: npm install
      
    - name: Build
      run: npm run build
      env: 
        CI: false

    - name: Workspace 
      run: pwd && ls -a

    - name: Prepare SSH
      run: >
          mkdir -p ~/.ssh &&
          touch ~/.ssh/known_hosts &&
          ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
      env:
        IP: ${{ env.SERVER_HOST }}    
      
    # 上传打包资源
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        ARGS: '-rltgoDzvO --delete'
        SOURCE: "dist/"
        REMOTE_HOST: ${{ env.SERVER_HOST }}
        REMOTE_USER: ${{ env.USER_NAME }}
        TARGET: "/home/ubuntu/front" # 服务器目标路径
    
